help:
	@echo "Available makes:"
	@echo "clean - remove unused files"

all:
	make clean

# Remove unused files
clean:
	rm *.aux *.bbl *.blg *.log *.bcf *.idx *.run.xml *.lof *.lot *.synctex.gz *.out *.toc
